#!/usr/bin/env bash
# Bash script that will display information about subdomains

domain() {
	dig "$2"."$1" | awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' | awk -v subdomain="$2" '{print "The subdomain " subdomain " is a " $4 " record and points to " $5 }'
	return 0
}
subdomains=("www" "18.234.105.35" "web-01" "18.210.20.138" "web-02" "34.204.61.126")

for subdomain in "${subdomains[@]}"
do
	if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
	then
	domain "$1" "$subdomain"
	fi
done
