#!/usr/bin/env bash
#configures a new Ubuntu machine to respect above requirements

sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html

service nginx restart
