#!/usr/bin/env bash
# configure a brand new server with nginx with redirection
# error page and X-Served by server name

# updates the package list & install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# allows Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# create directory & set permissions
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www

# creates two files; default page and error page
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo service nginx restart
