#!/usr/bin/env bash

# Install Nginx
sudo apt install nginx

# Edit the Nginx configuration file
sudo nano /etc/nginx/nginx.conf

# Add the following line to the http {} section:
add_header X-Served-By $hostname;

# Save and close the file.

# Restart Nginx
sudo service nginx restart
