#!/usr/bin/env bash
# install and comfigure a load balnacer
# with haproxy and roundrobin config

# update package and install HAProxy
sudo apt-get -y update
sudo apt-get install -y haproxy

apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "frontend myfrontend
\tbind 0.0.0.0:80
\tdefault_backend myservers

backend web_servers
        balance roundrobin
        server 244023-web-01 52.91.153.40:80 check
        server 244034-web-02 54.84.51.64:80 check
' >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy

# modify default Nginx configuration; add rewrite rule, error_page & header
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/ permanent;\n\n\terror_page 404 \/404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

# modify default Nginx configuration; add custom header
sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

# restart HAproxy service
sudo service haproxy restart
