#!/usr/bin/env bash
# This script displays the time from 0 hours to 12 hours and from 1 minute to 59 minutes.

hours=0
minutes=1
while [ $hours -ne 13 ]
do
    echo "Hour: $hours"
    ((hours++))
    while [ $minutes -ne 60 ]
    do
	echo $minutes
	((minutes++))
    done
    ((minutes = 1))
done
