#!/usr/bin/env bash
# This script displays the content of the current directory in a list format, showing only the part of the name after the first dash.

list=$(ls)
for count in $list
do
    echo "$count" | cut -d'-' -f 2
done
